name: jdot-ci-build
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:

  run-tests:

    strategy:
      matrix:
        python-version: [3.7, 3.9]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install jdot and pytest
      run: |
        pip install pytest
        python setup.py develop

    - name: Run tests
      run: pytest .

  fmt-lint:
    name: Style & lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: python3 -m pip install --upgrade pip black==22.3.0 flake8==4.0.1
    - name: Black
      run: python3 -m black --diff --check .
    - name: Flake8
      run: python3 -m flake8 .

  license:
    name: Check license headers
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check License Header
      uses: enarx/spdx@master
      with:
        licenses: Apache-2.0
