name: jsom-ci-build
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:

  run-tests:

    strategy:
      matrix:
        python-version: [3.6, 3.9]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install jsom and pytest
      run: |
        pip install pytest
        python setup.py develop

    - name: Run tests
      run: pytest .
